version: "3"
networks:
  mariadb:
    external:
      name: mariadb

services:
  mariadb-3t:
    image: mariadb:10.3.9
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - MYSQL_ROOT_PASSWORD=ypkWRE7kwHZd7GonmRdeoCzJ
      - MYSQL_DATABASE=tieuthantai
    volumes:
      - mariadb-3t:/var/lib/mysql
    command: ["--max_connections=1000"]
    ports:
      - 33061:3306
    networks:
      - mariadb
volumes:
  mariadb-3t:
    driver: nfs
    driver_opts:
      share: 47.52.229.63:/mariadb-3t
