version: "3"
networks:
  backend:

services:
  mariadb:
    image: mariadb:10.3.9
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=backup
    volumes:
      - mariadb:/var/lib/mysql:nocopy
    networks:
      - backend
  backup:
    image: kingdarkness/mysql-backup
    volumes:
      - ./backup:/backup
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MAX_BACKUPS=10
      - INIT_BACKUP=0
      - CRON_TIME=* * * * *
    networks:
      - backend
volumes:
  mariadb:
